### PR TITLE
[MSHARED-1195] update to Java 8 minimum

### PR DESCRIPTION
**Pull request by elharo**
spotless also did some trivial formatting

### CODE REVIEW

**Comment by elharo** [comment]
There appears to be a pre-existing formatting issue:

```
[INFO] Index file does not exist. Fallback to an empty index

WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by com.palantir.javaformat.java.JavacTokens$CommentSavingTokenizer (file:/home/jenkins/jenkins-home/workspace/n_maven-box_maven-shared-io_jdk8@2/.repository/com/palantir/javaformat/palantir-java-format/2.28.0/palantir-java-format-2.28.0.jar) to field com.sun.tools.javac.parser.JavaTokenizer.reader

WARNING: Please consider reporting this to the maintainers of com.palantir.javaformat.java.JavacTokens$CommentSavingTokenizer

WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

WARNING: All illegal access operations will be denied in a future release

[ERROR] Step 'palantir-java-format' found problem in 'src/test/java/org/apache/maven/shared/io/location/FileLocationTest.java':

error: Imports not contiguous (perhaps a comment separates them?)
```

**Review by michael-o — CHANGES_REQUESTED** [review]
This is not just a Java 8 update, this is a parent upgrade to 39 which does more than that.

**Comment by elharo** [comment]
I assumed the parent was previously blocked by JDK 7, but maybe removing that will bypass the broken spotless checks. Frankly, spotless is too buggy and I wish we weren't using it, but let me try.

**Comment by elharo** [comment]
Reverting the parent does seem to sidestep the spotless bug.

**Review by michael-o — APPROVED** [review]
Should have a JIRA issue to be visible in release notes.

**Comment by elharo** [comment]
added JIRA issue

**Comment by slachiewicz** [comment]
Jira should be in commit message

**Pull request merged**
