### PR TITLE
[MSHARED-1202] update to parent POM 39

### PR DESCRIPTION
**Pull request by elharo**
contains the usual automated spotless churn that this update requires.

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
check for duplicate license header:

```
git grep -c "Licensed to the Apache Software Foundation (ASF) under one" | grep -v ":1"
```

Good will be to have 2 commits - one with parent update and one with code reformat.
After merge we can add  commit with reformat to `.git-blame-ignore-revs`

https://maven.apache.org/pom/maven/#the-format-profile

**Review by elharo — COMMENTED** [review]
Thanks for the grep command. It found one duped license I had missed.

**Review by slawekjaranowski — APPROVED** [review]
Please prepare 2 commits - one with change and one with code reformat

**Comment by elharo** [comment]
It all gets squashed in the end. Separating the commits for the update and the reformatting leaves broken states in the history.

**Comment by jira-importer** [comment]
Resolve #55

**Pull request merged**
