### PR TITLE
[MSHARED-930] Fix SimpleResourceInclusionScanner.getIncludedSources() returns wrong…

### PR DESCRIPTION
**Pull request by dengliming**
[https://issues.apache.org/jira/browse/MSHARED-930](https://issues.apache.org/jira/browse/MSHARED-930)

### CODE REVIEW

**Comment by slachiewicz** [comment]
Please add also test case

**Comment by dengliming** [comment]
@slachiewicz Fixed at lastest commit. Thanks.

**Comment by slachiewicz** [comment]
merged, Found one more case `Collections.empty` was returning `Set<String>`.
Thx you.

**Comment by jira-importer** [comment]
Resolve #52

**Pull request closed without merging**
